import { toRowValues, type ClientRecord } from "./model";

/**
 * Seed rows for the demo tracker.
 *
 * Realistic enough that the dashboard shows what the client actually wants to see on a
 * Monday morning: who owes money, what is late, and what is sitting with a client for
 * review. A tracker with three tidy rows in it demonstrates nothing.
 */

const SEED: ClientRecord[] = [
  {
    clientId: "AMRL-0001",
    submittedAt: "2026-07-14T09:12:00.000Z",
    contactName: "Rosalind Achebe",
    company: "Harrow & Finch",
    email: "r.achebe@harrowfinch.example",
    phone: "+44 7700 900118",
    projectType: "Brand film",
    budgetGbp: 18500,
    deadline: "2026-09-30",
    brief: "Three-minute brand film for the autumn rebrand, plus six social cutdowns. Shooting at the Shoreditch office and the Leeds warehouse.",
    heardAbout: "Referral",
    driveFolderUrl: "https://drive.google.com/drive/folders/seed-0001",
    status: "Delivered",
    paymentStatus: "Paid in full",
    depositDue: "2026-07-21",
    amountPaidGbp: 18500,
    deliveryStatus: "Delivered",
    deliveredAt: "2026-09-26",
    owner: "Nadia",
    lastUpdated: "2026-09-26T16:40:00.000Z",
    notes: "Asked about a retainer for 2027. Worth a call in November.",
  },
  {
    clientId: "AMRL-0002",
    submittedAt: "2026-08-02T14:35:00.000Z",
    contactName: "Dev Raichura",
    company: "Northgate Coffee",
    email: "dev@northgatecoffee.example",
    phone: "07700 900241",
    projectType: "Photography",
    budgetGbp: 3200,
    deadline: "2026-10-10",
    brief: "Product photography for twelve SKUs plus lifestyle shots for the new website. Need transparent-background cutouts for the shop.",
    heardAbout: "Instagram",
    driveFolderUrl: "https://drive.google.com/drive/folders/seed-0002",
    status: "In production",
    paymentStatus: "Deposit paid",
    depositDue: "2026-08-09",
    amountPaidGbp: 1600,
    deliveryStatus: "With client for review",
    deliveredAt: "",
    owner: "Joel",
    lastUpdated: "2026-09-15T11:05:00.000Z",
    notes: "First selects sent 15 Sep. Waiting on their pick before retouching.",
  },
  {
    clientId: "AMRL-0003",
    submittedAt: "2026-08-19T08:02:00.000Z",
    contactName: "Marguerite Lowe",
    company: "Pellow Architects",
    email: "m.lowe@pellow.example",
    phone: "+44 7700 900377",
    projectType: "Website",
    budgetGbp: 24000,
    deadline: "2026-11-14",
    brief: "New portfolio site. Needs a project archive going back to 2004 and a case-study template the team can fill in themselves.",
    heardAbout: "LinkedIn",
    driveFolderUrl: "https://drive.google.com/drive/folders/seed-0003",
    status: "In production",
    paymentStatus: "Overdue",
    depositDue: "2026-08-26",
    amountPaidGbp: 0,
    deliveryStatus: "In progress",
    deliveredAt: "",
    owner: "Priya",
    lastUpdated: "2026-09-08T09:30:00.000Z",
    notes: "Deposit three weeks late. Chased twice. Do not book the shoot until it lands.",
  },
  {
    clientId: "AMRL-0004",
    submittedAt: "2026-09-01T16:48:00.000Z",
    contactName: "Toby Ferreira",
    company: "Silverline Gin",
    email: "toby@silverlinegin.example",
    phone: "07700 900462",
    projectType: "Social campaign",
    budgetGbp: 7400,
    deadline: "2026-10-31",
    brief: "Six-week paid social campaign for the Christmas range. Fifteen assets, three formats each, plus a hero film for the pre-roll.",
    heardAbout: "Existing client",
    driveFolderUrl: "https://drive.google.com/drive/folders/seed-0004",
    status: "Onboarding",
    paymentStatus: "Invoiced",
    depositDue: "2026-09-08",
    amountPaidGbp: 3700,
    deliveryStatus: "Not started",
    deliveredAt: "",
    owner: "Nadia",
    lastUpdated: "2026-09-12T13:20:00.000Z",
    notes: "Kickoff booked for the 22nd.",
  },
  {
    clientId: "AMRL-0005",
    submittedAt: "2026-09-16T10:21:00.000Z",
    contactName: "Wendy Okonjo",
    company: "Brambling Bakery",
    email: "wendy@bramblingbakery.example",
    phone: "",
    projectType: "Event coverage",
    budgetGbp: 1900,
    deadline: "2026-10-04",
    brief: "Coverage of the new bakery opening: stills plus a ninety-second reel for socials the same evening.",
    heardAbout: "Google",
    driveFolderUrl: "https://drive.google.com/drive/folders/seed-0005",
    status: "New enquiry",
    paymentStatus: "Awaiting deposit",
    depositDue: "2026-09-23",
    amountPaidGbp: 0,
    deliveryStatus: "Not started",
    deliveredAt: "",
    owner: "Joel",
    lastUpdated: "2026-09-16T10:21:00.000Z",
    notes: "",
  },
];

export const SEED_CLIENTS: ClientRecord[] = SEED;
export const SEED_ROWS: string[][] = SEED.map(toRowValues);
